name: Upload Translations to LingoHub

on:
    push:
        branches:
            - develop
        paths:
            - "messages/*.json"
    workflow_dispatch:

jobs:
    upload-translations:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - uses: ruby/setup-ruby@v1
              with:
                  ruby-version: "3.3"

            - name: Install LingoHub CLI
              run: gem install lingohub

            - name: Login to LingoHub
              run: |
                  mkdir -p ~/.lingohub/
                  echo "$LINGO_HUB_CREDENTIALS" > ~/.lingohub/credentials
              env:
                  LINGO_HUB_CREDENTIALS: ${{ secrets.LINGO_HUB_CREDENTIALS }}

            - name: Upload translations to LingoHub
              run: lingohub resource:up './messages/en-GB.json' --locale en --project AURORA-Dashboard
