name: Upload Translations to LingoHub

on:
    push:
        branches:
            - develop
        paths:
            - "messages/*.json"
    workflow_dispatch:

jobs:
    upload-translations:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - uses: actions/setup-ruby
              with:
                  ruby-version: "2.x"

            - name: Install LingoHub CLI
              run: gem install lingohub

            - name: Login to LingoHub
              run: |
                  mkdir -p ~/.lingohub/
                  echo "$LINGO_HUB_CREDENTIALS" > ~/.lingohub/credentials
              env:
                  LINGO_HUB_CREDENTIALS: ${{ secrets.LINGO_HUB_CREDENTIALS }}

            - name: Upload translations to LingoHub
              run: lingohub resource:up './messages/en-GB.json' --locale en-GB --project AURORA-Dashboard
